# Generated by Django 4.1.4 on 2023-01-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='set_password',
            field=models.BooleanField(default=True),
        ),
    ]
