# Generated by Django 4.1.4 on 2023-01-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_account_set_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='set_password',
        ),
    ]
