# Generated by Django 4.1.4 on 2022-12-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
